/* DROP VIEWS */

DROP VIEW MOVIE_RATING;
DROP VIEW MOVIE_REVIEW;

/* DROP INDEX */

DROP INDEX INDEX_GENRE;
DROP INDEX INDEX_TAGID;
DROP INDEX INDEX_MOVIE_LOCATIONS;

/* DROP TABLE  */

DROP TABLE USER_RATEDMOVIES CASCADE CONSTRAINTS PURGE;
DROP TABLE USER_RATEDMOVIES_TIMESTAMPS CASCADE CONSTRAINTS PURGE;
DROP TABLE USER_TAGGEDMOVIES CASCADE CONSTRAINTS PURGE;
DROP TABLE USER_TAGGEDMOVIES_TIMESTAMPS1 CASCADE CONSTRAINTS PURGE;
DROP TABLE MOVIE_TAGS CASCADE CONSTRAINTS PURGE;
DROP TABLE TAGS CASCADE CONSTRAINTS PURGE;
DROP TABLE MOVIE_LOCATIONS CASCADE CONSTRAINTS PURGE;
DROP TABLE MOVIE_COUNTRIES CASCADE CONSTRAINTS PURGE;
DROP TABLE MOVIE_ACTORS CASCADE CONSTRAINTS PURGE;
DROP TABLE MOVIE_DIRECTORS CASCADE CONSTRAINTS PURGE;
DROP TABLE MOVIE_GENRES CASCADE CONSTRAINTS PURGE;
DROP TABLE MOVIES CASCADE CONSTRAINTS PURGE;


