/* DROP TABLE QUERIES */


DROP TABLE REVIEW CASCADE CONSTRAINTS PURGE;
DROP TABLE IMDB_USER CASCADE CONSTRAINTS PURGE;
DROP TABLE ROLES CASCADE CONSTRAINTS PURGE;
DROP TABLE MOVIE_GENRE CASCADE CONSTRAINTS PURGE;
DROP TABLE GENRE CASCADE CONSTRAINTS PURGE;
DROP TABLE MOVIE CASCADE CONSTRAINTS PURGE;
DROP TABLE PERSON CASCADE CONSTRAINTS PURGE;


/* DROP VIEWS */

DROP VIEW HIGH_RATING;
DROP VIEW LOW_RATING;
DROP VIEW NO_FLOP;
DROP VIEW ALPACINO_MOVIES;
DROP VIEW ACTOR_LONGETIVITY;