/* 3. Print all information of the movies that have both 
a) the highest number of ratings; and 
b) the lowest average. */


SELECT MO.SERIAL_NO, MO.TITLE, MO.RELEASE_YEAR, MO.DIRECTOR, RA.RATING FROM MOVIE MO, REVIEW RA WHERE RA.RATING <= ALL(SELECT MIN(RA.RATING) FROM REVIEW RA, MOVIE MO WHERE RA.MOVIE_ID IN (SELECT R.MOVIE_ID FROM REVIEW R, MOVIE M WHERE M.SERIAL_NO = R.MOVIE_ID GROUP BY M.SERIAL_NO HAVING COUNT (M.SERIAL_NO) = (SELECT MAX (COUNT1) FROM (SELECT R.MOVIE_ID, COUNT(M.SERIAL_NO) COUNT1 FROM REVIEW R, MOVIE M WHERE M.SERIAL_NO = R.MOVIE_ID GROUP BY M.SERIAL_NO))) AND RA.MOVIE_ID = MO.SERIAL_NO) AND MO.SERIAL_NO = RA.MOVIE_ID ORDER BY MO.SERIAL_NO;

